---
title: "R의 기초"  
author: "Yoon-Ho Hong" 
date: "2023-08-06"
output: 
  html_document:
    toc: yes
    toc_float: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = F)
```

### 강의 목표

-   R과 RStudio 설치
-   R의 기본 문법 및 구조 이해
-   변수, 데이터 유형과 구조 학습
-   반복문, 조건문, 함수 등 기초 제어 구조 익히기
-   데이터 입출력 및 패키지 활용

## 1. R 설치

R은 "통계와 데이터 분석을 위한 프로그래밍 언어" 입니다.\
먼저 공식 웹사이트에서 R을 설치합니다.

[R 다운로드 및 설치](https://www.r-project.org/)

R은 계산기로도 활용 가능합니다.

```{r}
2 + 2
3^2
10 %% 3
```

------------------------------------------------------------------------

## 2. 변수와 연산자

```{r}
my_var <- 4  # 또는 my_var = 4
```

-   `<-`는 할당 연산자(assignment operator)입니다.
-   산술 연산자 예시:

```{r}
1 + 2
3 * 5
2^4
```

------------------------------------------------------------------------

## 3. RStudio 설치

[RStudio 다운로드 및 설치](https://www.rstudio.com/)

RStudio는 R 프로그래밍을 위한 통합 개발 환경(IDE)입니다.

------------------------------------------------------------------------

## 4. 데이터 유형 (Data Types)

```{r}
numeric_data <- 10.5
character_data <- "R is fun!"
boolean_data <- TRUE
```

------------------------------------------------------------------------

## 5. 데이터 구조 (Data Structures)

### Vector

```{r}
my_vec <- c(1, 2, 3)
my_vec[2]  # indexing
```

### Factor

```{r}
f <- factor(c("low", "medium", "high", "low"))
levels(f)
```

### Matrix

```{r}
m <- matrix(1:6, nrow=2)
m[1, 2]
```

### List

```{r}
lst <- list(name = "Kim", age = 30, scores = c(90, 95))
lst$age
```

### Data Frame

```{r}
df <- data.frame(name = c("Kim", "Lee"), age = c(30, 40))
df[1, ]
```

------------------------------------------------------------------------

## 6. 반복문과 조건문

### for loop

```{r}
sum_val <- 0
for (i in 1:10) {
  sum_val <- sum_val + i
}
sum_val
```

### while loop

```{r}
i <- 1
while (i <= 5) {
  print(i)
  i <- i + 1
}
```

### 조건문

```{r}
i <- 3
if (i > 2) {
  print("크다")
} else {
  print("작다")
}
```

------------------------------------------------------------------------

## 7. 함수

### 내장 함수

```{r}
x <- c(1, 3, 5, 7)
mean(x)
sort(x, decreasing = TRUE)
```

### 사용자 정의 함수

```{r}
square <- function(x) {
  return(x^2)
}
square(4)
```

------------------------------------------------------------------------

## 8. 환경 설정

```{r}
getwd()      # 현재 작업 경로 확인
setwd("./data") # 작업 경로 설정
ls()         # 현재 환경의 객체 보기
rm(list = ls()) # 객체 모두 삭제
```

------------------------------------------------------------------------

## 9. 패키지 사용

```{r eval=FALSE}
install.packages("dplyr")
library(dplyr)
```

------------------------------------------------------------------------

## 10. 데이터 불러오기와 저장

```{r}
df_csv <- read.csv("data/sample.csv")
head(df_csv)

write.csv(df_csv, "data/sample_output.csv", row.names = FALSE)
```

------------------------------------------------------------------------

## 11. R 종료하기

```{r eval=FALSE}
q()
```

작업 공간을 저장할지 묻는 창이 뜹니다. "Yes"를 선택하면 `.RData` 파일로 저장됩니다.
