<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Yoon-Ho Hong" />

<meta name="date" content="2022-08-30" />

<title>회귀(Regression)</title>

<script src="site_libs/header-attrs-2.13/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Data medicine with R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown-header">by Yoon H. Hong</li>
<li>
  <a href="http://www.github.com/yoonhohong/SnuDataMed">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">회귀(Regression)</h1>
<h4 class="author">Yoon-Ho Hong</h4>
<h4 class="date">2022-08-30</h4>

</div>


<p>이번 시간에는 선형 회귀 모델을 학습합니다.</p>
<p>선형 회귀는 최신의 기계학습 기법만큼 흥미롭지 않을 수도 있지만,
여전히 유용하고 자주 사용되는 방법입니다.</p>
<p>사실 많은 기계학습 기법이 선형회귀의 일반화 혹은 확장으로 볼 수
있습니다. 따라서, 더 복잡한 기계학습 기법에 대해 학습하기 전에
선형회귀에 대해 잘 이해하는 것이 매우 중요합니다.</p>
<div id="선형-회귀linear-regression" class="section level2">
<h2>선형 회귀(linear regression)</h2>
<p>선형회귀 모델을 gapminder 자료에 적용해 다음 질문들에 답해보기로
합시다.</p>
<ol style="list-style-type: decimal">
<li><p>일인당 국민소득과 기대수명은 상관관계가 있는가?</p></li>
<li><p>일인당 국민소득과 기대수명사이에 얼마나 강한 상관관계가
있는가?</p></li>
<li><p>기대수명에 대한 일인당 국민소득의 효과는 어느정도이며, 이
추정치는 얼마나 정확한가?</p></li>
<li><p>기대수명에 대해 얼마나 정확하게 예측할 수 있는가?</p></li>
</ol>
<p>필요한 패키지를 먼저 로딩하겠습니다.</p>
<pre class="r"><code>library(gapminder)
library(dplyr)
library(ggplot2)</code></pre>
<p>1952년 데이터를 추출해서 일인당 국민소득과 기대수명은 상관관계를
알아보기 위해 산점도를 먼저 그려보겠습니다.</p>
<pre class="r"><code>gapminder %&gt;%
  filter(year == 1952) %&gt;%
  ggplot(aes(gdpPercap, lifeExp)) + 
  geom_point()</code></pre>
<p><img src="Regression_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>x축 값들이 낮은 수치에 몰려있어, 로그변환을 하겠습니다.</p>
<pre class="r"><code>gapminder %&gt;%
  filter(year == 1952) %&gt;%
  ggplot(aes(gdpPercap, lifeExp)) + 
  geom_point() + 
  scale_x_log10()</code></pre>
<p><img src="Regression_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>직관적으로 일인당 국민소득과 기대수명은 상관관계가 있어보입니다.</p>
<p>이제, 앞서 제기했던 질문에 대해 답해보기로 합니다.</p>
</div>
<div id="상관관계-여부" class="section level2">
<h2>상관관계 여부</h2>
<blockquote>
<p>일인당 국민소득과 기대수명은 상관관계가 있는가?</p>
</blockquote>
<p>위 질문에 답하기 위해 우리는 다음 두 가지를 해야합니다.</p>
<ul>
<li>선형회귀 모델의 적합</li>
<li>가설 검정 <span class="math inline">\(\beta_x\)</span> = 0</li>
</ul>
<p>선형 회귀 모델을 적합시키는 함수로 lm()을 사용합니다.</p>
<pre class="r"><code>df_1952 = gapminder %&gt;%
  filter(year == 1952) %&gt;%
  select(gdpPercap, lifeExp) %&gt;%
  mutate(gdpPercap_log10 = log10(gdpPercap))
lm_1952 = lm(lifeExp ~ gdpPercap_log10, data = df_1952)</code></pre>
<p>통계적 모델링의 결과를 보기위해 summary() 함수를 사용합니다.</p>
<pre class="r"><code>summary(lm_1952)</code></pre>
<pre><code>## 
## Call:
## lm(formula = lifeExp ~ gdpPercap_log10, data = df_1952)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -28.9571  -5.7319   0.7517   6.5770  13.7361 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      -17.846      5.067  -3.522 0.000578 ***
## gdpPercap_log10   20.331      1.526  13.326  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.146 on 140 degrees of freedom
## Multiple R-squared:  0.5592, Adjusted R-squared:  0.556 
## F-statistic: 177.6 on 1 and 140 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>선형회귀를 적합시키기 위해 lm() 함수는 최소제곱법을 사용하는데,
최소제곱법은 잔차제곱합(residual sum of squares, RSS)을 최소화하는 계수
추정치를 구하는 방법입니다(미분을 사용함).</p>
<p>Coefficients에서 gdpPercap_log10에 해당하는 estimate (slope 추정치)와
표준오차가 얼마인지 확인해봅시다(<span
class="math inline">\(\beta_x\)</span> = 20.331, 표준 오차는 1.526).</p>
<p>선형 회귀 모델을 적합하면, <span
class="math inline">\(\beta_x\)</span> = 0 라는 귀무 가설에 대한 검정
결과도 제시되는데, 귀무 가설 검정에는 t-statistic 을 사용합니다.</p>
<p>t statistic은 는 아래와 같습니다.</p>
<p><span
class="math display">\[t=\frac{\overline{x}-\mu_o}{SE}\]</span></p>
<p><span class="math inline">\(\overline{x}\)</span>: sample mean
(coefficient in linear regression)<br />
<span class="math inline">\(\mu_0\)</span>: population mean (coefficient
in linear regression) SE: standard error (of the coefficient in linear
regression)</p>
<p><span class="math inline">\(\overline{x}\)</span> 는 최소제곱법(least
square method)으로 구했고, <span class="math inline">\(\mu_0\)</span> 는
귀무 가설에서 0 입니다(기울기가 0이라는 것은 상관관계가 없다는
뜻이므로)</p>
<p>계수 추정치의 표준오차는 아래에서 자세히 살펴보겠습니다.</p>
<p>자유도가 n-2 (=140)인 t 분포에서(n이 대략 30보다 크면 t 분포는
정규분포와 아주 유사) t 값이 위에서 구한 <span
class="math inline">\(|t|\)</span> 값보다 큰 경우를 관측할 확률(즉,
p-value)을 구함으로써 상관 관계를 유추할 수 있습니다.</p>
<p>즉, p-value 가 충분히 작으면(예를 들어, 0.05보다 작으면) 귀무가설을
기각하고 상관관계가 있다고 합니다.</p>
<p>일인당 국민소득과 기대수명의 예에서 t = 13.326, p-value &lt; 2e-16
이므로, 우리는 귀무가설을 기각하고, 일인당 국민소득과 기대수명간에는
통계적으로 유의한 상관관계가 있다고 말할 수 있습니다.</p>
</div>
<div id="모델-적합도" class="section level2">
<h2>모델 적합도</h2>
<blockquote>
<p>일인당 국민소득과 기대수명사이에 얼마나 강한 상관관계가 있는가?</p>
</blockquote>
<p>귀무가설을 기각하고 대립가설을 채택했다면, 모델이 데이터에 적합한
정도를 수량화하고자 할 것입니다.</p>
<p>선형회귀적합의 정도는 보통 잔차표준오차(RSE)와 <span
class="math inline">\(R^2\)</span> 통계량을 사용하여 표현합니다.</p>
<p>RSE는 위에서 살펴보았으니, <span class="math inline">\(R^2\)</span>
를 어떻게 구하는지 알아봅시다.</p>
<p><span class="math display">\[R^2 = \frac{TSS -
RSS}{TSS}\]</span><br />
TSS: Total sum of squares (aka, SS around the mean) RSS: Residual sum of
squares (aka, SS around the fit)</p>
<p>위 식에서 알 수 있듯이, <span class="math inline">\(R^2\)</span>는
반응변수의 전체 분산에서 회귀 모델에 의해 설명되는 변동의 비율을
말합니다.</p>
<p><span class="math inline">\(R^2\)</span>: the proportion of the total
variation explained by the fit (regression model)</p>
<p>위 예에서 <span class="math inline">\(R^2\)</span>는 0.5592입니다.
기대수명 변동의 56%는 일인당 국민소득(의 로그변환값)에 대한 단순선형회귀
모델로 설명된다는 뜻입니다.</p>
<p>adjusted <span class="math inline">\(R^2\)</span>는 모델의 예측변수의
수를 보정한 값입니다. 예측 변수의 수가 2개 이상인 다중 선형회귀
모델에서는 예측 변수와 설명변수의 상관 여부와 관계없이 예측 변수의
개수가 증가할 수도록 <span class="math inline">\(R^2\)</span>는
증가합니다. 따라서, 새로운 예측 변수가 추가됨에 따든 우연한 증가분을
보정해야 하는 것입니다.</p>
<p>선형회귀 모델의 적합도에 대한 통계적 검정은 F 분포를
이용합니다(모델의 특정 예측 변수와 반응 변수간의 상관 관계에 대한 검정은
t 분포를 이용).</p>
<p>F-statistic은 모델에 의해 설명되는 분산을 모델에 의해 설명되지 않는
분산으로 나눈 값입니다.</p>
<p>F 분포에서 F 값이 위에서 구한 F-statistic 값보다 큰 경우를 관측할
확률(즉, p-value)을 구함으로써 귀무가설에 대해 통계적 검정을 합니다. 즉,
p-value 가 충분히 작으면(예를 들어, 0.05보다 작으면) 귀무가설을
기각합니다.</p>
</div>
<div id="상관관계의-크기와-추정의-정확도" class="section level2">
<h2>상관관계의 크기와 추정의 정확도</h2>
<blockquote>
<p>기대수명에 대한 일인당 국민소득의 효과는 어느정도이며, 얼마나
정확하게 추정할 수 있는가?</p>
</blockquote>
<p>계수 추정치가 20.331입니다. 이는 log10(gdpPercap)가 1만큼 증가할
때(즉, 일인당 국민소득이 10배 증가할 때) 기대수명이 약 20년 증가한다는
것을 의미합니다.</p>
<p>이러한 추정치가 얼마나 정확한가에 대답하기 위해서는 표준오차를
살펴야합니다.</p>
<p>계수 추정치의 표준오차는 다음 식으로 구합니다.</p>
<p><span class="math display">\[SE(\hat{\beta_1}) =
\frac{\sigma}{\sqrt{\sum_{i=1}^{n}{(x_i-\overline{x})^2}}}\]</span></p>
<p><span class="math inline">\(\sigma\)</span>는 랜덤오차(random
error)의 표준편차를 가리키며, 그 추정치로 잔차표준오차(residual standard
error, RSE)를 사용합니다(<span class="math inline">\(RSE =
\sqrt{RSS/(n-2)}\)</span>)</p>
<p>위 식에서 직관적으로 표준오차는 RSS가 작을 수록, 그리고 <span
class="math inline">\(x_i\)</span>가 넓게 퍼질수록(기울기를 추정할
레버지리(leverage)가 크다고 합니다) 더 작아진다는 것을 알 수
있습니다.</p>
<p>일반적으로 표준오차는 신뢰구간(confidence interval)을 계산하는데
사용됩니다. 계수 추정치에 대한 95% 신뢰구간은 실제값(모집단에서의
기울기)이 95%의 확률로 존재하는 구간이며 대략 아래와 같은 형태를
가집니다.</p>
<p><span class="math display">\[[\hat{\beta_1}-2SE(\hat{\beta}), \space
\hat{\beta_1}+2SE(\hat{\beta})]\]</span></p>
<pre class="r"><code>confint(lm_1952, level = 0.95)</code></pre>
<pre><code>##                     2.5 %    97.5 %
## (Intercept)     -27.86295 -7.828398
## gdpPercap_log10  17.31506 23.347735</code></pre>
</div>
<div id="예측" class="section level2">
<h2>예측</h2>
<blockquote>
<p>기대수명에 대해 얼마나 정확하게 예측할 수 있는가?</p>
</blockquote>
<p>위에서 신뢰구간은 기대수명에 대한 일인당국민소득의 효과를 둘러싼
불확실성을 수량화하는 것입니다.</p>
<p>한편, 특정 국가의 기대수명에 대한 불확실성을 수량화하는데 관심이
있다면, 신뢰구간 대신 예측구간(prediction interval)을 사용해야
합니다.</p>
<p>예측구간은 신뢰구간보다 항상 더 넓습니다. 이유는 예측구간은 계수에
대한 추정오차(축소가능오차) 뿐만아니라 축소불가능 오차를 포함하기
때문입니다.</p>
<p>선형회귀 모델의 회귀 직선과 신뢰구간, 그리고 예측 구간을 모두
포함하는 산점도를 그려보겠습니다.</p>
<pre class="r"><code>predictions = predict(lm_1952, newdata = df_1952, interval = &quot;predict&quot;)
head(predictions)</code></pre>
<pre><code>##        fit      lwr      upr
## 1 40.94837 24.74135 57.15539
## 2 47.30439 31.13999 63.46878
## 3 51.05723 34.89220 67.22226
## 4 54.26202 38.08128 70.44276
## 5 58.83793 42.61063 75.06524
## 6 63.51481 47.21080 79.81881</code></pre>
<pre class="r"><code>df_pred = cbind(df_1952, predictions)
df_pred %&gt;%
  ggplot(aes(gdpPercap_log10, lifeExp)) + 
  geom_point() + 
  stat_smooth(method = &quot;lm&quot;, level = 0.95) + 
  geom_line(aes(y=lwr), col = &quot;red&quot;, linetype = &quot;dashed&quot;) + 
  geom_line(aes(y=upr), col = &quot;red&quot;, linetype = &quot;dashed&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="Regression_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<blockquote>
<p>1952년 데이터를 이용해 학습시킨 이 단순 선형회귀 모델을 이용해 2002년
기대수명을 예측해봅시다.</p>
</blockquote>
<pre class="r"><code>df_2002 = gapminder %&gt;%
  filter(year == 2002) %&gt;%
  select(lifeExp, gdpPercap) %&gt;%
  mutate(gdpPercap_log10 = log10(gdpPercap))</code></pre>
<p>예측값의 산출을 위해 predict() 함수를 사용합니다.</p>
<p>예측값과 실제 관측값이 얼마나 다른지 살펴봅시다.</p>
<pre class="r"><code>df = data.frame(obs = df_2002$lifeExp, prd = pred)
ggplot(df, aes(obs, prd)) + 
  geom_point() + 
  geom_abline(slope = 1, intercept = 0)</code></pre>
<p><img src="Regression_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>2002년 데이터 포인트들은 위 그림에서 직선(y=x) 아래 주로 분포되어
있습니다. 1952년 데이터로 학습한 모델을 2002년 데이터에 적용했을 때 기대
수명을 실제보다 낮게 예측하는 경향이 있다는 것을 알 수 있습니다.</p>
<p>회귀모델의 예측 정확도를 나타내는 정량 지표로 RMSE (Root mean squared
error)를 사용합니다.</p>
<p>rmse를 구하는 함수를 정의해봅시다.</p>
<pre class="r"><code>rmse = function(x){
  sqrt(sum((residuals(x)^2))/df.residual(x))
} # x &lt;- model object </code></pre>
<p>1952년 학습 데이터셋에서의 rmse를 구해봅시다.</p>
<pre class="r"><code>rmse(lm_1952)</code></pre>
<pre><code>## [1] 8.146311</code></pre>
<p>검정 데이터셋(test)에서의 rmse를 구해봅시다.</p>
<pre class="r"><code>lm_2002 = lm(obs ~ prd, data = df)
rmse(lm_2002) </code></pre>
<pre><code>## [1] 6.962083</code></pre>
<p>Confidence interval을 구해봅시다.</p>
</div>
<div id="더-생각해볼-문제들" class="section level2">
<h2>더 생각해볼 문제들</h2>
<p>교호 작용(interaction)</p>
<p>공선성(collinearity)</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
